# Generated by Django 2.0.2 on 2018-11-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20181101_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='users',
            new_name='user',
        ),
    ]
